#!/bin/bash
# This file was generated by auto-py-to-exe.
source .venv/bin/activate

pyinstaller --noconfirm --onefile --console --name "ASCII face cover" --collect-all "mediapipe" --hidden-import="PIL._tkinter_finder" --clean  "/home/nitzan/Documents/my shish/programming/python/ascii emoji face cover/main.py"
read -p "Press Enter to close..."
